<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Siscomex.Automacao.Core\Siscomex.Automacao.Core.csproj" />
    <ProjectReference Include="..\Siscomex.Automacao.Infrastructure\Siscomex.Automacao.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
